select = <"SELECT"> <ws> what (<ws> from)?
<what> = paren-selectable (<","> <ws> paren-selectable)*
<paren-selectable> = selectable | <"("> selectable <")">
<selectable> = probability | star
generate = <"GENERATE *"> (<ws> given)? <ws> <"FROM model">
probability = <"PROBABILITY OF"> <ws> (column | binding) (<ws> given)? <ws> <"FROM model">
star = <"*">
<from> = <"FROM"> <ws> <"("> generate <")"> <ws> limit
given = <"GIVEN"> <ws> (star | bindings)
<bindings> = binding (<ws> <"AND"> <ws> binding)*
<binding> = column <"="> value
<column> = #'[a-zA-Z_]+'
<value> = #'\"([^\"]+)\"'
limit = <"LIMIT"> <ws> nat
nat = #'[0-9]+'
ws = #'\s+'
